layout_spectrum: 0.4361702
color:
  saturation: 0.5531915
  brandStrength: 0.8015254
  lightness: 0.6148936
  rhythmicContrast: 0.5744681
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.5617021
name: Shuggeffect
