name: Shuggeffect
favicon: null
layout_spectrum: 0.33465
typography_spectrum: 0.60572
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3F4249'
    - '#FFFFFF'
    - '#9E968C'
    - '#C1BCB8'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
