name: Shuggeffect
favicon: null
layout_spectrum: 0.74944
typography_spectrum: 0.60572
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#134c1f'
    - '#e7d57f'
    - '#597828'
    - '#8b982f'
    - '#e4f4b6'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
purpose: []
